version: "3"

services:

  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    container_name: ${PROJECT_NAME}_db_adminer      
    image: adminer:${ADMINER_VERSION}
    restart: unless-stopped
    links:
      - db
    ports:
      - 8080:8080

  wordpress:
    container_name: ${PROJECT_NAME}_wordpress
    image: wordpress:${WORDPRESS_VERSION}
    restart: always
    links:
      - db
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 12345678
      WORDPRESS_DB_NAME: blog_db
    volumes:
      - wordpress:/var/www/html
        
  node_exporter:
    container_name: ${PROJECT_NAME}_node_exporter
    image: prom/node-exporter:${NODEEXPORTER_VERSION}
    restart: unless-stopped
    links:
      - db
      - wordpress
    command:
      - '--path.rootfs=/host'
    # ports:
    #   - 9100:9100
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    container_name: ${PROJECT_NAME}_prometheus
    image: prom/prometheus:${PROMETHEUS_VERSION}
    restart: always
    links:
      - node_exporter
    # ports:
    #   - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

  grafana:
    container_name: ${PROJECT_NAME}_grafana
    image: grafana/grafana:${GRAFANA_VERSION}
    restart: unless-stopped
    links:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/default.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./grafana/main.json:/var/lib/grafana/dashboards/main.json

volumes:
  mysql:
  wordpress:
  prometheus:
  grafana:
